"""
Career boards of large US employers, verified against each live board.

Derived from the `state-of-ats-2026` dataset
(github.com/Kayvan-Zahiri/state-of-ats-2026, MIT License, copyright its
authors), which names the careers host of 738 large employers. Only
US-headquartered rows were used. A host is not a board, so each was resolved on
2026-09-28:

* Workday: every career site the tenant's robots.txt lists — which is how
  sites like Salesforce's `Futureforce_NewGradRoles` are here — each then
  probed exactly as registry validation probes a board. 565 of 570 answered.
* Eightfold: the host is the board; probed through its PCSX search.
* iCIMS: the careers host names the slug; probed for a readable listing.

Oracle and SuccessFactors hosts were left out: a host alone does not name an
Oracle site, and the dataset lists none for SuccessFactors. Discovery finds
those from posting links and Common Crawl.

Each entry is `(board, company)`. Merged into `ats_seeds.SEED_ATS_SLUGS`, with
the company name filed on the registry row.

The dataset's notice, which its license asks to travel with it:

    MIT License

    Copyright (c) 2026 Kayvan Zahiri

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to
    deal in the Software without restriction, including without limitation the
    rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
    sell copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
    IN THE SOFTWARE.
"""

LARGE_EMPLOYER_BOARDS: dict[str, list[tuple[str, str]]] = {
    "workday": [
        ("3m:wd1:Search", "3M"),
        ("abbott:wd5:Agency", "Abbott"),
        ("abbott:wd5:abbottcareers", "Abbott"),
        ("abbott:wd5:abbottcareers2", "Abbott"),
        ("abbott:wd5:eQuest", "Abbott"),
        ("adobe:wd5:external_experienced", "Adobe"),
        ("adventhealth:wd12:AH_External_Career_Site", "AdventHealth"),
        ("aep:wd1:AEPCareerSite", "American Electric Power"),
        ("aig:wd1:aig", "AIG"),
        ("aig:wd1:early_careers", "AIG"),
        ("aig:wd1:japan", "AIG"),
        ("airproducts:wd5:AP0001", "Air Products"),
        ("airproducts:wd5:AP0003", "Air Products"),
        ("alcoa:wd5:Careers", "Alcoa"),
        ("allstate:wd5:Agent", "Allstate"),
        ("allstate:wd5:allstate_careers", "Allstate"),
        ("amcn:wd5:amcnetworks", "AMC Networks"),
        ("amgen:wd1:Careers", "Amgen"),
        ("amgen:wd1:agency", "Amgen"),
        ("att:wd1:ATTCollege", "AT&T"),
        ("att:wd1:ATTGeneral", "AT&T"),
        ("att:wd1:Cricket", "AT&T"),
        ("autodesk:wd1:Ext", "Autodesk"),
        ("autodesk:wd1:uni", "Autodesk"),
        ("bakerhughes:wd5:BakerHughes", "Baker Hughes"),
        ("bannerhealth:wd108:Careers", "Banner Health"),
        ("bannerhealth:wd108:sonoraquestcareers", "Banner Health"),
        ("baxter:wd1:baxter", "Baxter"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ALGERIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ARGENTINA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_AUSTRALIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_AUSTRIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_BAHRAIN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_BELGIUM", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_BOSNIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_BRAZIL", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_CANADA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_CHILE", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_COLOMBIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_COSTA_RICA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_CROATIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_CZECH_REPUBLIC", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_DENMARK", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_DOMINICAN_REPUBLIC", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_EGYPT", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_FINLAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_FRANCE", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_GERMANY", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_GHANA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_GREECE", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_HONG_KONG", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_HUNGARY", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_INDIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_INDONESIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_IRELAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ISRAEL", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ITALY", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_JAPAN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_JORDAN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_KENYA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_KOREA_REPUBLIC_OF", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_KUWAIT", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_LEBANON", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_LUXEMBOURG", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_MALAYSIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_MEXICO", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_MOROCCO", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_NETHERLANDS", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_NEW_ZEALAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_NORWAY", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_OMAN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_PERU", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_PHILIPPINES", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_POLAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_PORTUGAL", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_QATAR", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ROMANIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SAUDI_ARABIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SINGAPORE", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SLOVAKIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SOUTH_AFRICA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SPAIN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SWEDEN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_SWITZERLAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_TAIWAN", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_THAILAND", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_TUNISIA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_TURKEY", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_UK", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_UNITED_ARAB_EMIRATES", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_USA", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_VIETNAM", "Becton Dickinson"),
        ("bdx:wd1:EXTERNAL_CAREER_SITE_ZAMBIA", "Becton Dickinson"),
        ("bdx:wd1:US_EARLY_TALENT_SITE", "Becton Dickinson"),
        ("bdx:wd1:embectacareers", "Becton Dickinson"),
        ("blackrock:wd1:BlackRock_Professional", "BlackRock"),
        ("bloomenergy:wd1:BloomEnergyCareers", "Bloom Energy"),
        ("blueorigin:wd5:BlueOrigin", "Blue Origin"),
        ("boeing:wd1:AAEOY", "Boeing"),
        ("boeing:wd1:AISES", "Boeing"),
        ("boeing:wd1:ALPFA", "Boeing"),
        ("boeing:wd1:ASCEND", "Boeing"),
        ("boeing:wd1:BEYA", "Boeing"),
        ("boeing:wd1:CLEAR", "Boeing"),
        ("boeing:wd1:DA", "Boeing"),
        ("boeing:wd1:DIV", "Boeing"),
        ("boeing:wd1:DVST", "Boeing"),
        ("boeing:wd1:ENG", "Boeing"),
        ("boeing:wd1:EXTERNAL_CAREERS", "Boeing"),
        ("boeing:wd1:EXTERNAL_RECALL", "Boeing"),
        ("boeing:wd1:GMIS", "Boeing"),
        ("boeing:wd1:GRACE", "Boeing"),
        ("boeing:wd1:HIRE", "Boeing"),
        ("boeing:wd1:INCL", "Boeing"),
        ("boeing:wd1:INTERN", "Boeing"),
        ("boeing:wd1:LAT", "Boeing"),
        ("boeing:wd1:MFG", "Boeing"),
        ("boeing:wd1:NABA", "Boeing"),
        ("boeing:wd1:NAI", "Boeing"),
        ("boeing:wd1:NSBE", "Boeing"),
        ("boeing:wd1:PRIDE", "Boeing"),
        ("boeing:wd1:SASE", "Boeing"),
        ("boeing:wd1:SHPE", "Boeing"),
        ("boeing:wd1:SWE", "Boeing"),
        ("boeing:wd1:TAP1", "Boeing"),
        ("boeing:wd1:TAP2", "Boeing"),
        ("boeing:wd1:TAP3", "Boeing"),
        ("boeing:wd1:TAP4", "Boeing"),
        ("boeing:wd1:TAP5", "Boeing"),
        ("boeing:wd1:TAP_EVENT", "Boeing"),
        ("boeing:wd1:TECH", "Boeing"),
        ("boeing:wd1:USBLN", "Boeing"),
        ("boeing:wd1:VET", "Boeing"),
        ("boeing:wd1:WAI", "Boeing"),
        ("boeing:wd1:WMB", "Boeing"),
        ("boeing:wd1:WOCT", "Boeing"),
        ("boeing:wd1:external_subsidiary", "Boeing"),
        ("boeing:wd1:external_ukcontingentworker", "Boeing"),
        ("bristolmyerssquibb:wd5:BMS", "Bristol Myers Squibb"),
        ("bristolmyerssquibb:wd5:BMS_Events", "Bristol Myers Squibb"),
        ("broadcom:wd1:External_Career", "Broadcom"),
        ("burlington:wd5:BurlingtonCareers", "Burlington"),
        ("capitalone:wd12:Capital_One", "Capital One"),
        ("cardinalhealth:wd1:Contractor", "Cardinal Health"),
        ("cardinalhealth:wd1:EXT", "Cardinal Health"),
        ("cardinalhealth:wd1:EXT_GLOBAL", "Cardinal Health"),
        ("cardinalhealth:wd1:Navista", "Cardinal Health"),
        ("carrier:wd5:Union_Workers_Career_Page", "Carrier"),
        ("carrier:wd5:jobs", "Carrier"),
        ("carrier:wd5:kgs_jobs", "Carrier"),
        ("catalent:wd1:External", "Catalent"),
        ("catalent:wd1:UR", "Catalent"),
        ("catalent:wd1:external_DI", "Catalent"),
        ("cbrands:wd5:CBI_External_Careers", "Constellation Brands"),
        ("cbrlgroup:wd503:CrackerBarrelExternal", "Cracker Barrel"),
        ("cbrlgroup:wd503:MapleStreetExternal", "Cracker Barrel"),
        ("cengage:wd5:CengageEMEACareers", "Cengage"),
        ("cengage:wd5:CengageIndiaCareers", "Cengage"),
        ("cengage:wd5:CengageLATAMBrazilCareers", "Cengage"),
        ("cengage:wd5:CengageLATAMCareersSPN", "Cengage"),
        ("cengage:wd5:CengageNorthAmericaCareers", "Cengage"),
        ("centene:wd5:Centene_External", "Centene"),
        ("chevron:wd5:University", "Chevron"),
        ("chevron:wd5:jobs", "Chevron"),
        ("chipotle:wd5:ChipotleCareers", "Chipotle"),
        ("choicehotels:wd5:External", "Choice Hotels"),
        ("choicehotels:wd5:HotelExternal", "Choice Hotels"),
        ("choicehotels:wd5:SkyTouch", "Choice Hotels"),
        ("chrobinson:wd5:CHRobinson", "C.H. Robinson"),
        ("chrobinson:wd5:Contingent", "C.H. Robinson"),
        ("chrobinson:wd5:ContractorConversionSite", "C.H. Robinson"),
        ("chrobinson:wd5:InternConversionSite", "C.H. Robinson"),
        ("chrobinson:wd5:UNCFCareerSite", "C.H. Robinson"),
        ("cigna:wd5:cignacareers", "Cigna"),
        ("cisco:wd5:Cisco_Careers", "Cisco"),
        ("condenast:wd115:CondeCareers", "Conde Nast"),
        ("condenast:wd115:PubWorx_External_Career_Site", "Conde Nast"),
        ("conocophillips:wd1:ExternalCWAU", "ConocoPhillips"),
        ("conocophillips:wd1:eQuest", "ConocoPhillips"),
        ("cox:wd1:Cox_External_Career_Site_1", "Cox Communications"),
        ("crowdstrike:wd5:crowdstrikecareers", "CrowdStrike"),
        ("cvshealth:wd1:CVS_Health_Careers", "CVS Health"),
        ("cvshealth:wd1:Private_Postings_Intern_Conversion_ONLY", "CVS Health"),
        ("cvshealth:wd1:Private_Postings_Mergers_and_Acquisitions_ONLY", "CVS Health"),
        ("cw:wd1:Agency", "Cushman & Wakefield"),
        ("cw:wd1:CWServices", "Cushman & Wakefield"),
        ("cw:wd1:External", "Cushman & Wakefield"),
        ("danaher:wd1:DanaherJobs", "Danaher"),
        ("dennys:wd1:Dennys", "Denny's"),
        ("dennys:wd1:DennysCorporation", "Denny's"),
        ("dennys:wd1:KekesBreakfastCafe", "Denny's"),
        ("dinebrands:wd503:DineCareers", "Applebee's"),
        ("dinebrands:wd503:RestaurantCareerSite", "Applebee's"),
        ("disney:wd5:disneycareer", "ESPN"),
        ("dollartree:wd5:dollartreeca", "Dollar Tree"),
        ("dollartree:wd5:dollartreeus", "Dollar Tree"),
        ("dow:wd1:ExternalCareers", "Dow"),
        ("dowjones:wd1:DNU_NewsCorpMosaicDigitalCareers", "Dow Jones"),
        ("dowjones:wd1:DNU_News_Technology_Services_Career", "Dow Jones"),
        ("dowjones:wd1:Dow_Jones_Career", "Dow Jones"),
        ("dowjones:wd1:NCS_External_Careers_Site", "Dow Jones"),
        ("dowjones:wd1:New_York_Post_Careers", "Dow Jones"),
        ("dowjones:wd1:News24_Careers", "Dow Jones"),
        ("dowjones:wd1:News_Corp_Australia_Careers", "Dow Jones"),
        ("dowjones:wd1:News_Corp_Careers", "Dow Jones"),
        ("dowjones:wd1:News_Fund_Careers", "Dow Jones"),
        ("dowjones:wd1:SUN_US_Careers", "Dow Jones"),
        ("dowjones:wd1:Storyful_Careers", "Dow Jones"),
        ("dowjones:wd1:WSJ_External_Career", "Dow Jones"),
        ("draftkings:wd1:DraftKings", "DraftKings"),
        ("dukeenergy:wd1:Search", "Duke Energy"),
        ("dukeenergy:wd1:nosearch", "Duke Energy"),
        ("dupont:wd5:Confidential", "DuPont"),
        ("dupont:wd5:Jobs", "DuPont"),
        ("dupont:wd5:Jobs_Swiss", "DuPont"),
        ("dxctechnology:wd1:ASJobs", "DXC Technology"),
        ("dxctechnology:wd1:DXCJobs", "DXC Technology"),
        ("ebay:wd5:TCGPlayer_External_Career", "eBay"),
        ("edwards:wd5:EdwardsCareers", "Edwards Lifesciences"),
        ("elevancehealth:wd1:ANT", "Elevance Health"),
        ("elevancehealth:wd1:IRL", "Elevance Health"),
        ("elevancehealth:wd1:Legato_Ireland", "Elevance Health"),
        ("elevancehealth:wd1:Legato_Israel", "Elevance Health"),
        ("elevancehealth:wd1:carelonglobal_in", "Elevance Health"),
        ("elevancehealth:wd1:carelonglobal_ph", "Elevance Health"),
        ("equinix:wd1:Adecco", "Equinix"),
        ("equinix:wd1:Adecco_Personaldienstleistungen_GmbH", "Equinix"),
        ("equinix:wd1:Align_Technical_Resources", "Equinix"),
        ("equinix:wd1:Annapurna_HR", "Equinix"),
        ("equinix:wd1:BSI_People", "Equinix"),
        ("equinix:wd1:Boyd_Moore_Executive_Search", "Equinix"),
        ("equinix:wd1:Bradley-Morris_LLC_dba_Bradley-Morris_Inc", "Equinix"),
        ("equinix:wd1:Brix_Projects", "Equinix"),
        ("equinix:wd1:CDS_Recruitment", "Equinix"),
        ("equinix:wd1:Career_Design_Center", "Equinix"),
        ("equinix:wd1:Careertrotter", "Equinix"),
        ("equinix:wd1:Clifford_Baines", "Equinix"),
        ("equinix:wd1:DaijobGlobalRecruiting", "Equinix"),
        ("equinix:wd1:Datacenterpeople_Ltd", "Equinix"),
        ("equinix:wd1:Euro_London_Appointment", "Equinix"),
        ("equinix:wd1:Execuforce", "Equinix"),
        ("equinix:wd1:GDH_Consulting", "Equinix"),
        ("equinix:wd1:Golden_Searches_Information_Consultant", "Equinix"),
        ("equinix:wd1:HaysSpecialistRecruitmentJapan", "Equinix"),
        ("equinix:wd1:Heidrick_Struggles", "Equinix"),
        ("equinix:wd1:IQ_Telecom", "Equinix"),
        ("equinix:wd1:Intelligence", "Equinix"),
        ("equinix:wd1:JAC_Recruitment", "Equinix"),
        ("equinix:wd1:Magellan_Professional_Solutions", "Equinix"),
        ("equinix:wd1:ManpowerGroup", "Equinix"),
        ("equinix:wd1:Michael_Page_International", "Equinix"),
        ("equinix:wd1:Michael_Page_International_Japan_KK", "Equinix"),
        ("equinix:wd1:MorganMcKinley", "Equinix"),
        ("equinix:wd1:Mynavi_Corporation", "Equinix"),
        ("equinix:wd1:PMA_Recruitment", "Equinix"),
        ("equinix:wd1:PRECEPT", "Equinix"),
        ("equinix:wd1:PRS_Recruitment_Services", "Equinix"),
        ("equinix:wd1:Page_Personnel", "Equinix"),
        ("equinix:wd1:Page_Personnel_Deutschland_GmbH", "Equinix"),
        ("equinix:wd1:Pro-Unlimited", "Equinix"),
        ("equinix:wd1:Recruit_Agent", "Equinix"),
        ("equinix:wd1:Recruit_Career", "Equinix"),
        ("equinix:wd1:Recruit_Plus", "Equinix"),
        ("equinix:wd1:Robert_Half_International_Inc", "Equinix"),
        ("equinix:wd1:Robert_Walters_Pty_Ltd", "Equinix"),
        ("equinix:wd1:Skill_House", "Equinix"),
        ("equinix:wd1:Skillhouse_Staffing_Solutions_KK", "Equinix"),
        ("equinix:wd1:Soar_Consulting_Inc", "Equinix"),
        ("equinix:wd1:en_japan_inc", "Equinix"),
        ("equinix:wd1:enworld_Co_Ltd", "Equinix"),
        ("etsy:wd5:Depop_Careers", "Etsy"),
        ("etsy:wd5:Etsy_Careers", "Etsy"),
        ("etsy:wd5:Reverb_Careers", "Etsy"),
        ("expedia:wd108:search", "Vrbo"),
        ("fedex:wd1:FCC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FCC_External", "FedEx"),
        ("fedex:wd1:FDW-US_Targeted_Posting_Portal", "FedEx"),
        ("fedex:wd1:FDW_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FDW_EU_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FDW_EU_External_Career_Site", "FedEx"),
        ("fedex:wd1:FDW_External_Career_Site", "FedEx"),
        ("fedex:wd1:FDW_OpCo_Career_Site", "FedEx"),
        ("fedex:wd1:FFC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FFC_External", "FedEx"),
        ("fedex:wd1:FSC_Canada_Career_Site", "FedEx"),
        ("fedex:wd1:FSC_Canada_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN-APAC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN-EMEIA_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN_APAC_External", "FedEx"),
        ("fedex:wd1:FTN_CAN_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN_CAN_External", "FedEx"),
        ("fedex:wd1:FTN_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN_EMEIA_External", "FedEx"),
        ("fedex:wd1:FTN_External_Career_Site", "FedEx"),
        ("fedex:wd1:FTN_LAC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FTN_LAC_External", "FedEx"),
        ("fedex:wd1:FXC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXC_External_Targeted_Career_Site", "FedEx"),
        ("fedex:wd1:FXE-APAC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXE-Canada_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXE-Canada_External_Career_Site", "FedEx"),
        ("fedex:wd1:FXE-EU_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXE-EU_External", "FedEx"),
        ("fedex:wd1:FXE-LAC_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXE-LAC_External_Career_Site", "FedEx"),
        ("fedex:wd1:FXE-MEISA-External", "FedEx"),
        ("fedex:wd1:FXE-MEISA_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXE-US_External_Career_Site", "FedEx"),
        ("fedex:wd1:FXE-US_Pilot_Career_Site", "FedEx"),
        ("fedex:wd1:FXE_APAC_External", "FedEx"),
        ("fedex:wd1:FXF-Inc_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXF-MEX-External", "FedEx"),
        ("fedex:wd1:FXF-MEX_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXF_External_Career_Site", "FedEx"),
        ("fedex:wd1:FXO_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXO_External", "FedEx"),
        ("fedex:wd1:FXS-FXC_External_Career_Site", "FedEx"),
        ("fedex:wd1:FXS_Cross_OpCo", "FedEx"),
        ("fedex:wd1:FXS_External_Targeted_Career_Site", "FedEx"),
        ("fivebelow:wd1:fivebelowcareers", "Five Below"),
        ("fmc:wd12:FMC", "FMC"),
        ("fmc:wd12:Posting_Link", "FMC"),
        ("fox:wd1:Domestic", "Fox"),
        ("fox:wd1:FOXTVST_Central", "Fox"),
        ("fox:wd1:FOXTVST_EAST", "Fox"),
        ("fox:wd1:FOXTVST_WEST", "Fox"),
        ("geaerospace:wd5:GE_ExternalSite", "GE Aerospace"),
        ("geaerospace:wd5:Only_Confidential_Executive_Recruiting", "GE Aerospace"),
        ("geico:wd1:External", "Geico"),
        ("geico:wd1:GEAP", "Geico"),
        ("geico:wd1:GEAS", "Geico"),
        ("generalmotors:wd5:Careers_GM", "General Motors"),
        ("generalmotors:wd5:Careers_GM_Private", "General Motors"),
        ("generalmotors:wd5:Careers_TEI", "General Motors"),
        ("genpact:wd108:External_Careers", "Genpact"),
        ("genpact:wd108:campussite", "Genpact"),
        ("gevernova:wd5:Vernova_ExternalSite", "GE Vernova"),
        ("ghr:wd1:Lateral-US", "Bank of America"),
        ("ghr:wd1:Scoutt", "Bank of America"),
        ("ghr:wd1:lateral-apac", "Bank of America"),
        ("ghr:wd1:lateral-ba_continuum", "Bank of America"),
        ("ghr:wd1:lateral-canada", "Bank of America"),
        ("ghr:wd1:lateral-emea", "Bank of America"),
        ("ghr:wd1:lateral-latam", "Bank of America"),
        ("gilead:wd1:gileadcareers", "Gilead Sciences"),
        ("gilead:wd1:gileadhotjobcareers", "Gilead Sciences"),
        ("gilead:wd1:gileadoncologycareers", "Gilead Sciences"),
        ("gilead:wd1:kitepharmacareers", "Gilead Sciences"),
        ("globalhr:wd5:REC_RTX_Ext_Gateway", "Collins Aerospace"),
        ("globalhr:wd5:Union_Workers_Career_Page", "Collins Aerospace"),
        ("hpe:wd5:ACJobSite", "HPE"),
        ("hpe:wd5:Jobsathpe", "HPE"),
        ("hpe:wd5:WFMathpe", "HPE"),
        ("hpinc:wd5:HPINC", "HP Inc."),
        ("humana:wd5:CenterWell_External_Career_Site", "Humana"),
        ("humana:wd5:Humana_External_Career_Site", "Humana"),
        ("huron:wd1:huroncareers", "Huron Consulting"),
        ("illumina:wd1:illumina-careers", "Illumina"),
        ("illumina:wd1:illumina-earlycareers-europe", "Illumina"),
        ("illumina:wd1:illumina-universityrecruiting", "Illumina"),
        ("intel:wd1:External", "Intel"),
        ("iqvia:wd1:IQVIA", "IQVIA"),
        ("jbhunt:wd501:Careers", "J.B. Hunt"),
        ("jj:wd5:BorderUnionHiring", "Johnson & Johnson"),
        ("jj:wd5:DisplacedEmployees", "Johnson & Johnson"),
        ("jj:wd5:JJ", "Johnson & Johnson"),
        ("jj:wd5:NonCompetetiveHiring", "Johnson & Johnson"),
        ("jll:wd1:ContingentTalent", "JLL"),
        ("jll:wd1:brightstonecareers", "JLL"),
        ("jll:wd1:hallandkaycareers", "JLL"),
        ("jll:wd1:jllcareers", "JLL"),
        ("jll:wd1:jllcareerschina", "JLL"),
        ("jll:wd1:lasallecareers", "JLL"),
        ("jll:wd1:transitions", "JLL"),
        ("kbr:wd5:Frazer_Nash_Careers", "KBR"),
        ("kbr:wd5:HomeSafe_Careers", "KBR"),
        ("kbr:wd5:KBR_Careers", "KBR"),
        ("kimberlyclark:wd1:Arbex", "Kimberly-Clark"),
        ("kimberlyclark:wd1:Arbex_LinkedIn", "Kimberly-Clark"),
        ("kimberlyclark:wd1:GLOBAL", "Kimberly-Clark"),
        ("kimberlyclark:wd1:LinkedIn", "Kimberly-Clark"),
        ("kimberlyclark:wd1:XXX_EMEA", "Kimberly-Clark"),
        ("kimberlyclark:wd1:XXX_LAO", "Kimberly-Clark"),
        ("kimberlyclark:wd1:XXX_NA", "Kimberly-Clark"),
        ("kimberlyclark:wd1:equest", "Kimberly-Clark"),
        ("kla:wd1:AnnArbor", "KLA"),
        ("kla:wd1:Filmetrics", "KLA"),
        ("kla:wd1:Israel", "KLA"),
        ("kla:wd1:Penang_Semicon", "KLA"),
        ("kla:wd1:Search", "KLA"),
        ("kla:wd1:Taiwan", "KLA"),
        ("kla:wd1:UR", "KLA"),
        ("kohls:wd504:kohlscareers", "Kohl's"),
        ("labcorp:wd1:External", "LabCorp"),
        ("leidos:wd5:External", "Leidos"),
        ("lennar:wd1:Early_Careers", "Lennar"),
        ("lennar:wd1:Lennar_Jobs", "Lennar"),
        ("lilly:wd115:CMP", "Eli Lilly"),
        ("lilly:wd115:LLY", "Eli Lilly"),
        ("lilly:wd115:MAA", "Eli Lilly"),
        ("livenation:wd503:InsomniacExternalSite", "Live Nation"),
        ("livenation:wd503:LNExternalSite", "Live Nation"),
        ("livenation:wd503:RNExternalSite", "Live Nation"),
        ("livenation:wd503:TMExternalSite", "Live Nation"),
        ("marcusmillichap:wd108:MarcusMillichap", "Marcus & Millichap"),
        ("mars:wd3:ExternalPrivate1", "Mars"),
        ("massgeneralbrigham:wd1:MGBExternal", "Mass General Brigham"),
        ("massgeneralbrigham:wd1:PhysicianOrganization", "Mass General Brigham"),
        ("mastercard:wd1:Campus", "Mastercard"),
        ("mastercard:wd1:ContractorConversion", "Mastercard"),
        ("mastercard:wd1:CorporateCareers", "Mastercard"),
        ("mastercard:wd1:RYC", "Mastercard"),
        ("maxar:wd1:Cleared_Opportunities", "Maxar"),
        ("maxar:wd1:KTIS_Program", "Maxar"),
        ("maxar:wd1:New_Products", "Maxar"),
        ("maxar:wd1:Software_Engineers", "Maxar"),
        ("maxar:wd1:SpaceWrx", "Maxar"),
        ("maxar:wd1:Vantor", "Maxar"),
        ("maxar:wd1:actalent", "Maxar"),
        ("maxar:wd1:adamson_partners_limited", "Maxar"),
        ("maxar:wd1:evona", "Maxar"),
        ("maxar:wd1:fortitude_systems", "Maxar"),
        ("maxar:wd1:lanterisspace", "Maxar"),
        ("maxar:wd1:orchard", "Maxar"),
        ("maxar:wd1:specialty_recruitment", "Maxar"),
        ("maxar:wd1:the_judge_group", "Maxar"),
        ("maxar:wd1:vaco", "Maxar"),
        ("maxar:wd1:zrg_partners", "Maxar"),
        ("mckesson:wd3:Acquisition_Campus", "McKesson"),
        ("mckesson:wd3:CoverMyMeds_External_Careers", "McKesson"),
        ("mckesson:wd3:External_Careers", "McKesson"),
        ("mckesson:wd3:Ontada_Careers", "McKesson"),
        ("mckesson:wd3:SCRI_Careers", "McKesson"),
        ("mckesson:wd3:rxsscareers", "McKesson"),
        ("medtronic:wd1:MedtronicCareers", "Medtronic"),
        ("mgmresorts:wd5:Pool-Hiring-2021", "MGM Resorts"),
        ("modernatx:wd1:M_tx", "Moderna"),
        ("modernatx:wd1:M_tx_HSopt", "Moderna"),
        ("mpc:wd1:MPCCareers", "Marathon Petroleum"),
        ("msd:wd5:SearchJobs", "Merck"),
        ("mydpr:wd5:11212017", "DPR Construction"),
        ("nationwide:wd1:Nationwide_Career", "Nationwide"),
        ("nationwide:wd1:Nationwide_Career_India", "Nationwide"),
        ("nba:wd108:nbacareers", "NBA"),
        ("nvidia:wd5:NVIDIAExternalCareerSite", "NVIDIA"),
        ("panerabread:wd5:Panera_Careers", "Panera Bread"),
        ("papajohns:wd1:PapaJohnsCareers", "Papa John's"),
        ("parsons:wd5:Search", "Parsons"),
        ("pfizer:wd1:Canada_Only_External", "Pfizer"),
        ("pfizer:wd1:ContractorConversions", "Pfizer"),
        ("pfizer:wd1:Costa_Rica_External", "Pfizer"),
        ("pfizer:wd1:PfizerCareers", "Pfizer"),
        ("plugpower:wd5:Indeed", "Plug Power"),
        ("plugpower:wd5:Plug_Power_Inc", "Plug Power"),
        ("polaris:wd5:PolarisJobs", "Polaris"),
        ("polaris:wd5:TetonJobs", "Polaris"),
        ("priceline:wd1:BookingHoldings", "Priceline"),
        ("priceline:wd1:Priceline", "Priceline"),
        ("priceline:wd1:Priceline-CollegeHiring", "Priceline"),
        ("prologis:wd5:Broadbean_CareerSite", "Prologis"),
        ("prologis:wd5:Prologis_External_Careers", "Prologis"),
        ("pultegroup:wd1:PGI", "PulteGroup"),
        ("qualcomm:wd12:External", "Qualcomm"),
        ("raymondjames:wd1:RaymondJamesCareers", "Raymond James"),
        ("raymondjames:wd1:RaymondJamesEarlyCareers", "Raymond James"),
        ("redhat:wd5:Jobs", "Red Hat"),
        ("regeneron:wd1:Careers", "Regeneron"),
        ("regeneron:wd1:IrelandPrivate", "Regeneron"),
        ("regeneron:wd1:US_Only_University_Relations_Career", "Regeneron"),
        ("rockwellautomation:wd1:External-ERGs", "Rockwell Automation"),
        ("rockwellautomation:wd1:External-Rockwell-Automation-Early-Careers", "Rockwell Automation"),
        ("rockwellautomation:wd1:External_Rockwell_Automation", "Rockwell Automation"),
        ("sabre:wd1:SabreJobs", "Sabre"),
        ("sabre:wd1:confidential", "Sabre"),
        ("salesforce:wd12:Datorama", "Salesforce"),
        ("salesforce:wd12:External_Career_Site", "Salesforce"),
        ("salesforce:wd12:Futureforce_Internships", "Salesforce"),
        ("salesforce:wd12:Futureforce_NewGradRoles", "Salesforce"),
        ("salesforce:wd12:Heroku", "Salesforce"),
        ("salesforce:wd12:Mulesoft_Careersite", "Salesforce"),
        ("salesforce:wd12:Salesforce_Research", "Salesforce"),
        ("salesforce:wd12:Slack", "Salesforce"),
        ("salesforce:wd12:Tableau", "Salesforce"),
        ("sands:wd1:sands_careers", "Las Vegas Sands"),
        ("sbdinc:wd1:Stanley_Black_Decker_Career_Site", "Stanley Black & Decker"),
        ("shakeshack:wd5:External", "Shake Shack"),
        ("sierraspace:wd1:Sierra_Space_External_Career_Site", "Sierra Space"),
        ("simon:wd1:Simon", "Simon Property Group"),
        ("simon:wd1:TMLO", "Simon Property Group"),
        ("sonos:wd1:Sonos", "Sonos"),
        ("sonos:wd1:Student_Opportunities", "Sonos"),
        ("spe:wd1:SonyPicturesEntertainment", "Sony Pictures"),
        ("stanfordmedicine:wd115:SHC_External_Career_Site", "Stanford Health"),
        ("stanfordmedicine:wd115:SHC_Tri-Valley_External_Careers", "Stanford Health"),
        ("stanfordmedicine:wd115:UHA_External_Careers", "Stanford Health"),
        ("statestreet:wd1:Global", "State Street"),
        ("statestreet:wd1:eQuest", "State Street"),
        ("strideinc:wd1:G", "Stride"),
        ("strideinc:wd1:MC", "Stride"),
        ("strideinc:wd1:SK", "Stride"),
        ("strideinc:wd1:T", "Stride"),
        ("strideinc:wd1:TE", "Stride"),
        ("stryker:wd1:StrykerAgencySite", "Stryker"),
        ("stryker:wd1:StrykerCareers", "Stryker"),
        ("sunrun:wd5:Sunrun_Careers", "Sunrun"),
        ("synchronyfinancial:wd5:AgencyCareerSite", "Synchrony"),
        ("synchronyfinancial:wd5:University", "Synchrony"),
        ("target:wd5:targetcareers", "Target"),
        ("thehartford:wd5:Careers_External", "Hartford Financial"),
        ("thehartford:wd5:Careers_Restricted", "Hartford Financial"),
        ("travelers:wd5:External", "Travelers"),
        ("travelers:wd5:SimplyBusinesssExternal", "Travelers"),
        ("tysonfoods:wd5:CVT", "Tyson Foods"),
        ("tysonfoods:wd5:TEPI", "Tyson Foods"),
        ("tysonfoods:wd5:TSN", "Tyson Foods"),
        ("tysonfoods:wd5:TSN1", "Tyson Foods"),
        ("usaa:wd1:CONFIDENTIAL", "USAA"),
        ("usaa:wd1:USAAJOBSWD", "USAA"),
        ("usbank:wd1:Elavon_Careers", "U.S. Bank"),
        ("usbank:wd1:US_Bank_Careers", "U.S. Bank"),
        ("vanguard:wd5:contractors_restricted", "Vanguard"),
        ("vanguard:wd5:vanguard_external", "Vanguard"),
        ("veradigm:wd12:VR", "Veradigm"),
        ("visa:wd5:Visa", "Visa"),
        ("visa:wd5:Visa_Early_Careers", "Visa"),
        ("warnerbros:wd5:francais", "Warner Bros. Discovery"),
        ("warnerbros:wd5:global", "Warner Bros. Discovery"),
        ("washpost:wd5:WashingtonPostCareersArc", "Washington Post"),
        ("washpost:wd5:washingtonpostcareers", "Washington Post"),
        ("werner:wd501:ECM", "Werner Enterprises"),
        ("werner:wd501:MCS", "Werner Enterprises"),
        ("werner:wd501:Roadmaster", "Werner Enterprises"),
        ("werner:wd501:Werner", "Werner Enterprises"),
        ("wiley:wd1:leadership", "Wiley"),
        ("wiley:wd1:wiley_careers", "Wiley"),
        ("williams:wd5:ContingentWorkerConvCareers", "Williams Companies"),
        ("williams:wd5:External", "Williams Companies"),
        ("williams:wd5:PowerExternal", "Williams Companies"),
        ("wmg:wd1:WMGAGENCY", "Warner Music Group"),
        ("wmg:wd1:WMGGERMANY", "Warner Music Group"),
        ("wmg:wd1:WMGGLOBAL", "Warner Music Group"),
        ("wmg:wd1:WMGUS", "Warner Music Group"),
        ("workday:wd5:Workday", "Workday"),
        ("workday:wd5:Workday_Early_Career", "Workday"),
        ("workday:wd5:Workday_Executive_Site", "Workday"),
        ("workday:wd5:Workday_Jobs", "Workday"),
        ("wwecorp:wd5:IMG", "UFC"),
        ("wwecorp:wd5:On_Location", "UFC"),
        ("wwecorp:wd5:PBR", "UFC"),
        ("wwecorp:wd5:PRIVATE_Postings", "UFC"),
        ("wwecorp:wd5:TKO", "UFC"),
        ("wwecorp:wd5:UFC", "UFC"),
        ("wwecorp:wd5:wweagency", "UFC"),
        ("wwecorp:wd5:wwecorp", "UFC"),
        ("wwecorp:wd5:zuffaboxing", "UFC"),
        ("xboxgaming:wd1:Blizzard_External_Careers", "Activision Blizzard"),
        ("xboxgaming:wd1:CentralTech", "Activision Blizzard"),
        ("xboxgaming:wd1:DL_external", "Activision Blizzard"),
        ("xboxgaming:wd1:External", "Activision Blizzard"),
        ("xboxgaming:wd1:HOH", "Activision Blizzard"),
        ("xboxgaming:wd1:King_External_Careers", "Activision Blizzard"),
        ("xboxgaming:wd1:SS_external", "Activision Blizzard"),
        ("xcelenergy:wd1:External", "Xcel Energy"),
        ("zendesk:wd1:zendesk", "Zendesk"),
        ("zillow:wd5:Zillow_Group_External", "Zillow"),
    ],
    "eightfold": [
        ("apply.careers.microsoft.com", "Microsoft"),
        ("careers.deere.com", "John Deere"),
        ("careers.lamresearch.com", "Lam Research"),
        ("elcompanies.eightfold.ai", "Estee Lauder"),
        ("jobs.kraftheinz.com", "Kraft Heinz"),
        ("micron.eightfold.ai", "Micron"),
        ("morganstanley.eightfold.ai", "Morgan Stanley"),
        ("slb.eightfold.ai", "SLB"),
        ("starbucks.eightfold.ai", "Starbucks"),
        ("whirlpool.eightfold.ai", "Whirlpool"),
    ],
    "icims": [
        ("generaldynamics", "General Dynamics"),
        ("kbhome", "KB Home"),
        ("mlssoccer", "MLS"),
        ("pepsico", "PepsiCo"),
        ("steeldynamics", "Steel Dynamics"),
        ("suffolkconstruction", "Suffolk Construction"),
    ],
}
